# Generated by Django 4.1.7 on 2023-10-03 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('idade', models.IntegerField()),
                ('variantes', models.ManyToManyField(related_name='pacientes', to='variantes.variante')),
            ],
        ),
    ]
