# Generated by Django 4.1.7 on 2023-10-03 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cromossomo', models.CharField(max_length=255)),
                ('base_nitrogenada', models.CharField(choices=[('A', 'A'), ('T', 'T'), ('C', 'C'), ('G', 'G')], default='A', max_length=10)),
                ('posicao', models.IntegerField()),
                ('base_referencia', models.CharField(choices=[('A', 'A'), ('T', 'T'), ('C', 'C'), ('G', 'G')], default='A', max_length=10)),
                ('base_alternativa', models.CharField(choices=[('A', 'A'), ('T', 'T'), ('C', 'C'), ('G', 'G')], default='A', max_length=10)),
            ],
            options={
                'verbose_name': 'Variante genética',
                'verbose_name_plural': 'Variantes genéticas',
            },
        ),
    ]
