# Generated by Django 4.1.7 on 2023-10-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantes', '0002_remove_variante_base_nitrogenada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
