# Generated by Django 4.1.7 on 2023-10-03 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('variantes', '0003_alter_variante_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
